[CmdletBinding()]
param (
    [Parameter(Mandatory=$true)]
    [string]$Path,
    [string]$ManualSample
)

if ($ManualSample -eq "")
{
    $generateReference = $true
}

$outGetPcap = New-TemporaryFile
$outFgt2eth = New-TemporaryFile

Get-Pcap -infile $Path -outfile $outGetPcap.FullName
$testedHash = $(Get-FileHash -Path $outGetPcap.FullName -Algorithm SHA1).Hash

if ($generateReference)
{
    .\fgt2eth.exe -in $Path -out $outFgt2eth.FullName >$null <# suppress commentary from fgt2eth.exe#>
    $referenceHash = $(Get-FileHash -Path $outFgt2eth.FullName -Algorithm SHA1).Hash
    Remove-Item .\output.tmp <#generated by fgt2eth.exe#>
}
else
{
    $referenceHash = $(Get-FileHash -Path $ManualSample -Algorithm SHA1).Hash
}

Write-Verbose "Tested   : $testedHash"
Write-Verbose "Reference: $referenceHash"

if ($testedHash -eq $referenceHash)
{
    Write-Output "SUCCESS: equal outputs"
}
else
{
    Write-Output "FAILED: outputs differ!"
}
#cleanup
Remove-Item $outGetPcap.FullName
Remove-Item $outFgt2eth.FullName